# Generated by Django 3.1.5 on 2021-10-29 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidoPaterno', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido Paterno')),
                ('apellidoMaterno', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido Materno')),
                ('nivelEscolar', models.CharField(max_length=20, verbose_name='Nivel escolar')),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['nombre', 'apellidoPaterno', 'apellidoMaterno'],
            },
        ),
        migrations.CreateModel(
            name='EncargadoLegal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Encargado Legal',
                'verbose_name_plural': 'Encargados Legales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('alumnos', models.ManyToManyField(related_name='maestro', to='administracion.Alumno')),
            ],
            options={
                'verbose_name': 'Maestro',
                'verbose_name_plural': 'Maestros',
                'ordering': ['apellido'],
            },
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.municipio')),
            ],
            options={
                'verbose_name': 'Escuela',
                'verbose_name_plural': 'Escuelas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='escargado_legal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='administracion.encargadolegal'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='escuela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.escuela'),
        ),
    ]
