# Generated by Django 3.1.5 on 2021-10-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('direccionFisica', models.CharField(blank=True, max_length=100, null=True, verbose_name='Direccion Física')),
                ('direccionPostal', models.CharField(blank=True, max_length=100, null=True, verbose_name='Direccion Postal')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('fax', models.CharField(max_length=200)),
                ('direccionFisica', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección Física')),
                ('direccionPostal', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección Postal')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
