# Generated by Django 3.2.8 on 2021-10-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroGestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Centro de Gestion',
                'verbose_name_plural': 'Centros de Gestion',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(choices=[('tutoria', 'Tutoría'), ('seguimiento', 'Seguimiento'), ('mentoria', 'Mentoría'), ('conserjeria', 'Conserjería'), ('jd', 'JD')], default='tutoria', max_length=50)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['nombre'],
            },
        ),
    ]
