# Generated by Django 3.1.5 on 2021-11-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_maestro_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='maestro',
            options={'ordering': ['apellido'], 'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
    ]
