# Generated by Django 3.2.8 on 2021-10-22 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_alter_servicio_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoMaestro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.alumno')),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.maestro')),
            ],
        ),
    ]
