# Generated by Django 3.2.8 on 2021-10-22 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_alunomaestro'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlunoMaestro',
            new_name='AlumnoMaestro',
        ),
    ]
