# Generated by Django 3.1.5 on 2021-11-19 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_auto_20211119_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestro',
            name='cargo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='administracion.cargo'),
            preserve_default=False,
        ),
    ]
