# Generated by Django 3.2.8 on 2021-10-26 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_rename_alunomaestro_alumnomaestro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlumnoMaestro',
        ),
    ]
