# Generated by Django 3.1.5 on 2021-11-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_maestro_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='emailEncargado',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='nombreEncargado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='telefonoEncargado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
