# Generated by Django 3.1.5 on 2021-11-19 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_auto_20211119_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='escargado_legal',
        ),
    ]
