# Generated by Django 3.1.5 on 2021-11-19 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0007_remove_alumno_escargado_legal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EncargadoLegal',
        ),
    ]
