# Generated by Django 3.1.5 on 2021-11-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0008_delete_encargadolegal'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='tipoEncargado',
            field=models.CharField(choices=[('Madre', 'Madre'), ('Padre', 'Padre'), ('Otro', 'Otro')], default='Madre', max_length=32),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='emailEncargado',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Email del Encargado Legal'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombreEncargado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre del Encargado Legal'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='telefonoEncargado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Teléfono del Encargado Legal'),
        ),
    ]
