# Generated by Django 3.1.5 on 2022-01-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0009_auto_20211119_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='att',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='numeroFiscal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número Fiscal'),
        ),
    ]
