# Generated by Django 3.1.5 on 2022-01-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0010_auto_20220110_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroGestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Centro de Gestión',
                'verbose_name_plural': 'Centros de Gestión',
                'ordering': ['nombre'],
            },
        ),
    ]
