# Generated by Django 3.1.5 on 2022-01-10 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0011_centrogestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='centroGestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='administracion.centrogestion'),
        ),
    ]
