# Generated by Django 3.1.5 on 2022-01-31 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0012_cliente_centrogestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'ordering': ['nombre', 'apellidoPaterno', 'apellidoMaterno'], 'verbose_name': 'Participante', 'verbose_name_plural': 'Participantes'},
        ),
    ]
