# Generated by Django 3.1.5 on 2022-03-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0014_auto_20220211_0915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maestro',
            options={'ordering': ['apellido'], 'verbose_name': 'Consultor Educativo', 'verbose_name_plural': 'Consultores Educativos'},
        ),
        migrations.AlterField(
            model_name='maestro',
            name='alumnos',
            field=models.ManyToManyField(related_name='maestro', to='administracion.Alumno', verbose_name='Participantes'),
        ),
    ]
