# Generated by Django 3.1.5 on 2021-10-29 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fechaCreacion', models.DateTimeField(auto_now=True)),
                ('nroPartidaPresupuestaria', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='ServiciosProyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('precio_por_hora', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('cantidad_participantes', models.IntegerField(default=0)),
                ('total_horas', models.IntegerField(default=0)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyecto.proyecto')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyecto.servicio')),
            ],
            options={
                'verbose_name': 'Servicios del Proyecto',
                'verbose_name_plural': 'Servicios del Proyecto',
            },
        ),
    ]
