# Generated by Django 3.1.5 on 2021-10-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_cliente_proveedor'),
        ('proyecto', '0002_proyecto_serviciosproyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='alumnos',
            field=models.ManyToManyField(related_name='proyecto', to='administracion.Alumno'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='maestros',
            field=models.ManyToManyField(related_name='proyecto', to='administracion.Maestro'),
        ),
    ]
