# Generated by Django 3.1.5 on 2022-01-10 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_auto_20211029_1651'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CentroGestion',
        ),
    ]
