# Generated by Django 3.1.5 on 2022-01-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_delete_centrogestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciosproyecto',
            name='partidaPresupuestaria',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
