# Generated by Django 3.1.5 on 2022-01-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_serviciosproyecto_partidapresupuestaria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviciosproyecto',
            old_name='partidaPresupuestaria',
            new_name='partida_presupuestaria',
        ),
        migrations.AddField(
            model_name='serviciosproyecto',
            name='presupuesto_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
