# Generated by Django 3.1.5 on 2022-01-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_auto_20220112_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciosproyecto',
            name='presupuesto_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
