# Generated by Django 3.1.5 on 2022-01-12 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0007_auto_20220112_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviciosproyecto',
            name='partida_presupuestaria',
        ),
    ]
