# Generated by Django 3.1.5 on 2022-01-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0008_remove_serviciosproyecto_partida_presupuestaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre del Proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nroPartidaPresupuestaria',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Número de Partida Presupuestaria'),
        ),
    ]
