# Generated by Django 3.1.5 on 2022-02-01 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0009_auto_20220113_0842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['nombre'], 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='serviciosproyecto',
            options={'ordering': ['proyecto', 'servicio'], 'verbose_name': 'Servicios del Proyecto', 'verbose_name_plural': 'Servicios del Proyecto'},
        ),
    ]
