# Generated by Django 3.1.5 on 2022-02-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0010_auto_20220201_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='logoCliente',
            field=models.ImageField(null=True, upload_to='logos'),
        ),
    ]
