# Generated by Django 3.1.5 on 2022-02-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0011_proyecto_logocliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='logoAdmin1',
            field=models.ImageField(null=True, upload_to='logos'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='logoAdmin2',
            field=models.ImageField(null=True, upload_to='logos'),
        ),
    ]
