# Generated by Django 3.1.5 on 2022-02-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0012_auto_20220209_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='logoAdmin1',
            field=models.ImageField(null=True, upload_to='logos', verbose_name='Logo Uno a Uno Admin'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='logoAdmin2',
            field=models.ImageField(null=True, upload_to='logos', verbose_name='Logo Wioa Admin'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='logoCliente',
            field=models.ImageField(null=True, upload_to='logos', verbose_name='Logo del Cliente'),
        ),
    ]
