# Generated by Django 3.1.5 on 2022-02-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0014_auto_20220211_0915'),
        ('proyecto', '0013_auto_20220209_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='alumnos',
            field=models.ManyToManyField(related_name='proyecto', to='administracion.Alumno', verbose_name='Participantes'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='maestros',
            field=models.ManyToManyField(related_name='proyecto', to='administracion.Maestro', verbose_name='Personas'),
        ),
    ]
