# Generated by Django 3.1.5 on 2022-02-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0014_auto_20220215_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='logoAdmin1',
            field=models.ImageField(blank=True, null=True, upload_to='logos', verbose_name='Logo Uno a Uno Admin'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='logoAdmin2',
            field=models.ImageField(blank=True, null=True, upload_to='logos', verbose_name='Logo WIOA Admin'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='logoCliente',
            field=models.ImageField(blank=True, null=True, upload_to='logos', verbose_name='Logo del Cliente'),
        ),
        migrations.AlterField(
            model_name='serviciosproyecto',
            name='precio_por_hora',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Precio por participante'),
        ),
    ]
