# Generated by Django 3.1.5 on 2022-03-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0015_auto_20220317_1043'),
        ('proyecto', '0015_auto_20220224_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='nroPartidaPresupuestaria',
        ),
        migrations.AddField(
            model_name='serviciosproyecto',
            name='nroPartidaPresupuestaria',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Número de Partida Presupuestaria'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='maestros',
            field=models.ManyToManyField(related_name='proyecto', to='administracion.Maestro', verbose_name='Consultores Educativos'),
        ),
        migrations.AlterField(
            model_name='serviciosproyecto',
            name='cantidad_participantes',
            field=models.IntegerField(default=0, verbose_name='Límite de participantes'),
        ),
    ]
