# Generated by Django 3.1.5 on 2022-09-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0016_auto_20220317_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviciosproyecto',
            name='precio_por_hora',
        ),
        migrations.AddField(
            model_name='serviciosproyecto',
            name='precio_por_hora_participante',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Precio'),
        ),
        migrations.AddField(
            model_name='serviciosproyecto',
            name='tipo_facturacion',
            field=models.CharField(blank=True, choices=[('Por hora', 'Por hora'), ('Por participante', 'Por participante')], default='', max_length=32, verbose_name='Tipo de Facturación'),
        ),
    ]
