# Generated by Django 3.1.5 on 2022-09-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0017_auto_20220906_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciosproyecto',
            name='tipo_facturacion',
            field=models.CharField(choices=[('Por hora', 'Por hora'), ('Por participante', 'Por participante')], default='', max_length=32, verbose_name='Tipo de Facturación'),
        ),
    ]
