# Generated by Django 6.0.3 on 2026-04-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0018_auto_20220906_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciosproyecto',
            name='precio_por_hora_participante',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Precio (por Hora | Participante)'),
        ),
        migrations.AlterField(
            model_name='serviciosproyecto',
            name='total_horas',
            field=models.IntegerField(default=0, verbose_name='Total de horas por participante'),
        ),
    ]
