# Generated by Django 4.2.21 on 2026-04-09 20:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0019_alter_serviciosproyecto_precio_por_hora_participante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciosproyecto',
            name='cantidad_participantes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Límite de participantes'),
        ),
        migrations.AlterField(
            model_name='serviciosproyecto',
            name='total_horas',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total de horas por participante'),
        ),
    ]
