# Generated by Django 3.2.8 on 2021-10-25 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0005_rename_alunomaestro_alumnomaestro'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroHora',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaHoraInicio', models.DateTimeField()),
                ('fechaHoraFin', models.DateTimeField()),
                ('comentario', models.CharField(blank=True, max_length=400, null=True)),
                ('facturado', models.BooleanField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.alumno')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.servicio')),
            ],
        ),
    ]
