# Generated by Django 3.1.5 on 2021-10-29 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='estudiante',
            new_name='alumno',
        ),
    ]
