# Generated by Django 3.2.8 on 2021-10-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrohora',
            name='facturado',
            field=models.BooleanField(null=True),
        ),
    ]
