# Generated by Django 3.1.5 on 2021-10-29 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_auto_20211029_1651'),
        ('registros', '0002_auto_20211029_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='fechaHoraFin',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='fechaHoraInicio',
        ),
        migrations.AddField(
            model_name='registro',
            name='proyecto_servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='proyecto.serviciosproyecto'),
            preserve_default=False,
        ),
    ]
