# Generated by Django 3.2.8 on 2021-10-26 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_alter_registrohora_facturado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrohora',
            name='facturado',
        ),
    ]
