# Generated by Django 3.1.5 on 2021-11-02 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_auto_20211029_1651'),
        ('registros', '0003_auto_20211029_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='proyecto_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyecto.serviciosproyecto', verbose_name='Proyecto y Servicio'),
        ),
        migrations.CreateModel(
            name='RegistroDetalle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaHoraInicio', models.DateTimeField()),
                ('fechaHoraFin', models.DateTimeField()),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registros.registro')),
            ],
        ),
    ]
