# Generated by Django 3.2.8 on 2021-10-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_remove_registrohora_facturado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrohora',
            name='fechaHoraFin',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='registrohora',
            name='fechaHoraInicio',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
