# Generated by Django 3.1.5 on 2021-10-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_auto_20211026_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrohora',
            name='fechaHoraFin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='registrohora',
            name='fechaHoraInicio',
            field=models.DateTimeField(),
        ),
    ]
