# Generated by Django 3.1.5 on 2021-11-24 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0009_auto_20211119_1424'),
        ('registros', '0004_auto_20211102_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaCreacion', models.DateTimeField()),
                ('fechaInicio', models.DateTimeField()),
                ('fechaFin', models.DateTimeField()),
                ('eliminada', models.BooleanField()),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('terminosPago', models.CharField(blank=True, choices=[('Due upon reciept', 'Due upon reciept'), ('Net 30 days', 'Net 30 days'), ('Other', 'Other')], default='', max_length=32)),
                ('saleTax', models.CharField(blank=True, max_length=15, null=True)),
                ('mensajeInstitucional', models.CharField(blank=True, max_length=500, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.cliente')),
            ],
        ),
    ]
