# Generated by Django 3.1.5 on 2021-11-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='terminosPagoOtro',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='saleTax',
            field=models.CharField(blank=True, choices=[('Si (0%)', 'Si (0%)'), ('Si (10.5%)', 'Si (10.5%)'), ('No', 'No')], default='', max_length=15, null=True),
        ),
    ]
