# Generated by Django 3.1.5 on 2021-11-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0006_auto_20211126_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
