# Generated by Django 3.1.5 on 2021-11-26 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0009_auto_20211119_1424'),
        ('registros', '0007_auto_20211126_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='administracion.proveedor'),
            preserve_default=False,
        ),
    ]
