# Generated by Django 3.1.5 on 2021-11-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0008_factura_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='eliminada',
            field=models.BooleanField(default=False),
        ),
    ]
