# Generated by Django 3.1.5 on 2021-11-29 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0009_auto_20211126_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodetalle',
            name='factura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='registros.factura'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factura',
            name='mensajeInstitucional',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Mensaje Institucional'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='saleTax',
            field=models.CharField(blank=True, choices=[('Si (0%)', 'Si (0%)'), ('Si (10.5%)', 'Si (10.5%)'), ('No', 'No')], default='', max_length=15, null=True, verbose_name='Taxes'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='terminosPago',
            field=models.CharField(blank=True, choices=[('Due upon reciept', 'Due upon reciept'), ('Net 30 days', 'Net 30 days'), ('Other', 'Other')], default='', max_length=32, verbose_name='Terminos de Pago'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='terminosPagoOtro',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ingrese le nombre'),
        ),
    ]
