# Generated by Django 3.1.5 on 2021-11-30 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0011_registrodetalle_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrodetalle',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registros.factura'),
        ),
    ]
