# Generated by Django 3.1.5 on 2022-01-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0012_auto_20211130_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='terminosPagoOtro',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Términos Otros'),
        ),
    ]
