# Generated by Django 3.1.5 on 2022-01-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0013_auto_20220110_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodetalle',
            name='comentario',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
