# Generated by Django 3.1.5 on 2022-01-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0014_registrodetalle_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='descripcionTareas',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción de Tareas'),
        ),
        migrations.AddField(
            model_name='factura',
            name='logrosObtenidos',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Logros Obtenidos'),
        ),
        migrations.AddField(
            model_name='factura',
            name='saleTaxOtro',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tax Otro (%)'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='saleTax',
            field=models.CharField(blank=True, choices=[('Si (0%)', 'Si (0%)'), ('Si (10.5%)', 'Si (10.5%)'), ('No', 'No'), ('Other', 'Other')], default='', max_length=15, null=True, verbose_name='Taxes'),
        ),
    ]
