# Generated by Django 3.1.5 on 2022-01-10 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_delete_centrogestion'),
        ('registros', '0015_auto_20220110_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='proyecto_servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='proyecto.serviciosproyecto', verbose_name='Proyecto y Servicio'),
            preserve_default=False,
        ),
    ]
