# Generated by Django 3.1.5 on 2022-01-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0007_auto_20220112_0743'),
        ('registros', '0016_factura_proyecto_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='proyecto_servicio',
        ),
        migrations.AddField(
            model_name='factura',
            name='proyectosServicios',
            field=models.ManyToManyField(related_name='factura', to='proyecto.ServiciosProyecto'),
        ),
    ]
