# Generated by Django 3.1.5 on 2022-01-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0017_auto_20220112_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='saleTaxOtro',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='Tax Otro (%)'),
        ),
    ]
