# Generated by Django 3.1.5 on 2022-01-31 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0013_auto_20220131_0847'),
        ('registros', '0018_auto_20220113_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='factura',
            name='saleTax',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='saleTaxOtro',
        ),
        migrations.AlterField(
            model_name='factura',
            name='terminosPago',
            field=models.CharField(blank=True, choices=[('Due upon reciept', 'Due upon reciept'), ('Net 30 days', 'Net 30 days'), ('Other', 'Other')], default='', max_length=32, verbose_name='Términos de Pago'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.alumno', verbose_name='Participante'),
        ),
    ]
