# Generated by Django 3.1.5 on 2022-01-31 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0019_auto_20220131_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='impuesto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='registros.impuesto'),
            preserve_default=False,
        ),
    ]
