# Generated by Django 3.1.5 on 2022-01-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0020_factura_impuesto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impuesto',
            options={'ordering': ['nombre'], 'verbose_name': 'Impuesto', 'verbose_name_plural': 'Impuestos'},
        ),
        migrations.AddField(
            model_name='impuesto',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
