# Generated by Django 3.1.5 on 2022-02-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0022_auto_20220201_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='registrodetalle',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
